Added validation for high and low value fields for add item page
hack4impact-utk/mission-of-hope pull request #125
Opened 2024-04-19 20:59 UTC by Manan-dev

# Description

-> Added validation for high and low value fields for add item page.
-> Added dollar sign adornment

## Relevant issue(s)

#117 
## Questions

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have assigned reviewers to this PR

2024-04-19 23:30 UTC, AlanKha submitted a review, later dismissed

2024-04-19 23:30 UTC, AlanKha commented
Looks good to me

2024-04-20 04:39 UTC, alay10 requested changes

2024-04-20 04:39 UTC, alay10 commented on src/views/addItemView/index.tsx
> +import TopBar from '@/components/top-bar';
Not used

2024-04-20 04:39 UTC, alay10 commented on src/views/addItemView/index.tsx
> +              <FormControl fullWidth sx={{ m: 1 }}>
Unless you added this for a reason, the margin should probably stay 0

2024-04-20 04:39 UTC, alay10 commented on src/views/addItemView/index.tsx
> +              <FormControl fullWidth sx={{ m: 1 }}>
Same on this line

2024-04-20 17:42 UTC, alay10 approved these changes
Looks good!

2024-04-20 17:42 UTC, merged