52 home page
hack4impact-utk/mission-of-hope pull request #137
Opened 2024-04-20 19:41 UTC by jMcMaho9

# Description

## Relevant issue(s)

## Questions

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have assigned reviewers to this PR

2024-04-20 20:20 UTC, alay10 requested changes

2024-04-20 20:20 UTC, alay10 commented on src/app/page.tsx
> +            href="./Item"
changed all of the links to lowercase

2024-04-20 20:27 UTC, jMcMaho9 commented on src/app/page.tsx
> -            Inventory
donationItem

2024-04-20 20:27 UTC, jMcMaho9 commented on src/app/page.tsx
> +            href="./User"
./user

2024-05-07 08:01 UTC, alay10 approved these changes

2024-05-07 08:01 UTC, merged