View Users Page
hack4impact-utk/mission-of-hope pull request #77
Opened 2024-03-21 22:12 UTC by baekay000

# Description
Uses a card using mui that is centered and stacked. Tested using example users.

## Relevant issue(s)
Not sure about this.

## Questions

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

2024-04-01 23:36 UTC, alay10 requested changes
This looks good, I would like for you to change `<h1>` and `<p>` to the typography element from MUI see [this pr](https://github.com/hack4impact-utk/mission-of-hope/pull/68)

2024-04-01 23:36 UTC, alay10 commented on src/app/user/page.tsx
> +                <h2 style={{ display: 'flex', justifyContent: 'center' }}>
These are the sections I would change

2024-04-09 04:07 UTC, alay10 approved these changes
Nice job! Looks great

2024-04-09 04:10 UTC, Trishu-Patel approved these changes

2024-04-09 04:10 UTC, merged